Added Repository and Automapper
IlliaIliashenko/Iliashenko_illia pull request #41
Opened 2021-08-25 14:38 UTC by IlliaIliashenko

2021-08-25 16:58 UTC, IgorSerdiuk requested changes

2021-08-25 16:58 UTC, IgorSerdiuk commented on JWT_Auth_sample/BusinessLogicLayer/Services/GameService.cs
> +                    await _gameRepository.CreateAsync(_mapper.Map<FightResult>(new FightResultBL() { Loser = "User", Winner = "Ai", Result = "Ai wins" }));
Ненужный маппинг, ты создаешь FigthResult BL и маппишь его в FightResult вместо того, чтобы просто создать FightResult

2021-08-25 16:58 UTC, IgorSerdiuk commented on JWT_Auth_sample/BusinessLogicLayer/Services/CarShopService.cs
> +            var all = await GetAll();
ЧТО ЭТО ТАКОЕ ?! Представь что у тебя 50 миллионов машин.... 
ты КАЖДУЮ Достанешь из БД, смаппишь, и потом в памяти начнешь их фильтровать... ай ай ай...

2021-08-25 16:58 UTC, IgorSerdiuk commented on JWT_Auth_sample/BusinessLogicLayer/Services/GameService.cs
> +            var result = _mapper.Map<IEnumerable<FightResultBL>>(await _gameRepository.GetAllAsync());
ОПять все в памяти опять достаешь, потом маппишь, чтобы взять один

2021-08-25 16:58 UTC, IgorSerdiuk commented on JWT_Auth_sample/BusinessLogicLayer/Services/GameService.cs
>          public async Task PostFightResult(UserChoice post)
Вообще мне кажется, что лучше ты бы тут просто возвращал этот результат.... и использовал его на UI сразу, чем испльзовать метод GetLastResult из UI

2021-08-25 16:58 UTC, IgorSerdiuk commented on JWT_Auth_sample/BusinessLogicLayer/ViewModels/Game/FightResultBL.cs
> +    public class FightResultBL
чисто гипотетически, тебе не не нужен loser ибо по победителю понятно кто проиграл. только зря память кушаешь. вообще это все можно было бы описать одним bool полем 

IsUserWinner :D

2021-08-25 16:58 UTC, IgorSerdiuk commented on JWT_Auth_sample/BusinessLogicLayer/Services/GameService.cs
>          private readonly Dictionary<string, string> _gameResult = new Dictionary<string, string>()
это уже не нужно

2021-08-25 16:58 UTC, IgorSerdiuk commented on JWT_Auth_sample/BusinessLogicLayer/Services/GameService.cs
> +        private GameRepository _gameRepository;
Репозиторий тоже должен быть внедрен как интерфейс

2021-08-25 16:58 UTC, IgorSerdiuk commented on JWT_Auth_sample/JwtAuthSampleAPI/Models/Game/PostModel.cs
>      public class PostModel
По названию вообще не понятно что это за модель

2021-08-25 16:58 UTC, IgorSerdiuk commented on JWT_Auth_sample/JwtAuthSampleAPI/Models/Game/PostModel.cs
>      public class PostModel
и Id - в этом случае тоже вводит в заблужение

2021-08-30 14:11 UTC, IhorSerdiuk approved these changes

2021-09-08 07:19 UTC, merged